baseURL = "https://www.wahahockey.org"
title = "Westborough Amateur Hockey Association"
languageCode = "en-us"
paginate = 10

[params]
  org_name = "Westborough Amateur Hockey Association"
  org_short = "WAHA"
  description = "Supporting youth hockey development in Westborough, Massachusetts. Join our community-focused programs for players of all skill levels."
  
  # Donation configuration - Update this with your actual donation platform URL
  # Popular options: Givebutter, Donorbox, PayPal Giving Fund
  donate_url = "https://www.paypal.com/donate/?hosted_button_id=YOUR_BUTTON_ID"  # UPDATE THIS
  
  # Google Calendar embed (replace with your actual calendar ID)
  calendar_embed = "https://calendar.google.com/calendar/embed?src=YOUR_PUBLIC_CALENDAR_ID&mode=AGENDA"
  
  # Theme settings
  defaultTheme = "auto"  # light/dark based on user preference
  disableThemeToggle = false
  favicon = "/favicon.png"
  images = ["/images/social-card.png"]

  # Homepage settings
  ShowReadingTime = true
  ShowShareButtons = true

  # Homepage hero section
  [params.homeInfoParams]
    Title = "Westborough Amateur Hockey"
    Content = "Building character through hockey. Supporting our community's young athletes with quality programs, coaching, and opportunities. **2025–26 season registration now open!**"

  # Social media links (update with actual URLs)
  [[params.socialIcons]]
    name = "facebook"
    url = "https://facebook.com/wahahockey"  # UPDATE THIS
  [[params.socialIcons]]
    name = "mail"
    url = "mailto:info@wahahockey.org"  # UPDATE THIS

# Navigation menu
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Programs"
    url = "/programs/"
    weight = 2

  [[menu.main]]
    name = "News"
    url = "/news/"
    weight = 3

  [[menu.main]]
    name = "Media"
    url = "/media/"
    weight = 4

  [[menu.main]]
    name = "Events"
    url = "/events/"
    weight = 5

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 6

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 7
