backend:
  name: github
  repo: Fp4Mail/wahahockeyprod
  branch: main
  auth_type: implicit
  app_id: Ov23li4JiYlsbjCpz0b7

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "news"
    label: "📰 News Articles"
    folder: "content/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: true
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
        hint: "Keep titles clear and engaging"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
        default: "{{now}}"
      - label: "Featured Image"
        name: "image"
        widget: "image"
        required: false
        hint: "Upload a photo related to the article"
      - label: "Article Content"
        name: "body"
        widget: "markdown"
        hint: "Write your article here. Use the toolbar for formatting."

  - name: "media"
    label: "📸 Media & Videos"
    folder: "content/media"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Date"
        name: "date"
        widget: "datetime"
        default: "{{now}}"
      - label: "Description"
        name: "body"
        widget: "markdown"
        hint: "Describe what's in the photos/video"
      - label: "YouTube Link"
        name: "youtube_url"
        widget: "string"
        required: false
        hint: "Paste YouTube video URL here"

  - name: "events"
    label: "📅 Events & Games"
    folder: "content/events"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: "Event Title"
        name: "title"
        widget: "string"
      - label: "Event Date"
        name: "date"
        widget: "datetime"
      - label: "Location"
        name: "location"
        widget: "string"
        hint: "Rink name and address"
      - label: "Description"
        name: "body"
        widget: "markdown"

  - name: "pages"
    label: "📄 Website Pages"
    files:
      - file: "content/about.md"
        label: "About Page"
        name: "about"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Body"
            name: "body"
            widget: "markdown"
      
      - file: "content/donate.md"
        label: "Donation Page"
        name: "donate"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Body"
            name: "body"
            widget: "markdown"
      
      - file: "content/programs.md"
        label: "Programs Page"
        name: "programs"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Body"
            name: "body"
            widget: "markdown"

      - file: "content/contact.md"
        label: "Contact Info"
        name: "contact"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Body"
            name: "body"
            widget: "markdown"
