backend:
  name: github
  repo: Fp4Mail/wahahockeyprod  # UPDATE: Replace with your actual GitHub username/repo
  branch: main

# IMPORTANT: Update the repo name above with your actual GitHub repository

media_folder: "static/uploads"
public_folder: "/uploads"

# Easy content management for volunteers
collections:
  - name: "news"
    label: "📰 News Articles"
    folder: "content/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: true
    fields:
      - {label: "Title", name: "title", widget: "string", hint: "Keep titles clear and engaging"}
      - {label: "Publish Date", name: "date", widget: "datetime", default: "{{now}}"}
      - {label: "Featured Image", name: "image", widget: "image", required: false, hint: "Upload a photo related to the article"}
      - {label: "Summary", name: "description", widget: "string", required: false, hint: "Brief summary for social media sharing"}
      - {label: "Article Content", name: "body", widget: "markdown", hint: "Write your article here. Use the toolbar for formatting."}
      - {label: "Tags", name: "tags", widget: "list", required: false, hint: "Add relevant tags like 'clinic', 'tournament', 'registration'"}

  - name: "media"
    label: "📸 Media & Videos"
    folder: "content/media"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime", default: "{{now}}"}
      - {label: "Type", name: "media_type", widget: "select", options: ["Photo Gallery", "Video", "Live Stream", "Highlights"], default: "Photo Gallery"}
      - {label: "Description", name: "body", widget: "markdown", hint: "Describe what's in the photos/video"}
      - {label: "YouTube Link", name: "youtube_url", widget: "string", required: false, hint: "Paste YouTube video URL here"}
      - {label: "Google Photos Album", name: "photos_url", widget: "string", required: false, hint: "Link to Google Photos album"}
      - {label: "Cover Image", name: "image", widget: "image", required: false}

  - name: "events"
    label: "📅 Events & Games"
    folder: "content/events"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: true
    fields:
      - {label: "Event Title", name: "title", widget: "string"}
      - {label: "Event Date", name: "date", widget: "datetime"}
      - {label: "Location", name: "location", widget: "string", hint: "Rink name and address"}
      - {label: "Event Type", name: "event_type", widget: "select", options: ["Game", "Practice", "Tournament", "Clinic", "Meeting", "Fundraiser"]}
      - {label: "Age Group", name: "age_group", widget: "string", required: false, hint: "e.g., U10, U12, All Ages"}
      - {label: "Description", name: "body", widget: "markdown"}
      - {label: "Registration Required?", name: "registration_required", widget: "boolean", default: false}
      - {label: "Registration Link", name: "registration_url", widget: "string", required: false}

  - name: "pages"
    label: "📄 Website Pages"
    files:
      - file: "content/_index.md"
        label: "🏠 Homepage"
        name: "homepage"
        fields:
          - {label: "Page Title", name: "title", widget: "string"}
          - {label: "Hero Title", name: "hero_title", widget: "string", hint: "Main headline on homepage"}
          - {label: "Hero Description", name: "hero_description", widget: "text", hint: "Subtitle under main headline"}
          - {label: "Page Content", name: "body", widget: "markdown"}

      - file: "content/about.md"
        label: "ℹ️ About WAHA"
        name: "about"
        fields:
          - {label: "Page Title", name: "title", widget: "string"}
          - {label: "Page Content", name: "body", widget: "markdown", hint: "Tell the story of WAHA, our mission, and history"}

      - file: "content/programs.md"
        label: "🏒 Programs"
        name: "programs"
        fields:
          - {label: "Page Title", name: "title", widget: "string"}
          - {label: "Page Content", name: "body", widget: "markdown", hint: "Describe all hockey programs offered"}

      - file: "content/donate.md"
        label: "💝 Donation Page"
        name: "donate"
        fields:
          - {label: "Page Title", name: "title", widget: "string"}
          - {label: "Page Content", name: "body", widget: "markdown", hint: "Explain how donations help and impact levels"}

      - file: "content/contact.md"
        label: "📞 Contact Info"
        name: "contact"
        fields:
          - {label: "Page Title", name: "title", widget: "string"}
          - {label: "Page Content", name: "body", widget: "markdown", hint: "Contact information, board members, key contacts"}

# Show helpful editor interface
publish_mode: editorial_workflow
show_preview_links: true
